[project]
name = "HailRiskAT"
version = "1.0.0"
description = ""
authors = [
    {name = "Gregor Ehrensperger, Marc Falkensteiner", email = "gregor.ehrensperger@student.uibk.ac.at, marc.falkensteiner@datalabhell.at"},
]
dependencies = [
    "basemap>=1.3.8",
    "basemap-data-hires>=1.3.2",
    "cartopy>=0.22",
    "cmasher>=1.9.2",
    "dask>=2023.11",
    "geopandas>=0.14.1",
    "geopy>=2.4.1",
    "h5py>=3.10",
    "inquirer>=3.1.4",
    "ipympl>=0.10",
    "ipython>=8.18.1",
    "ipywidgets>=8.1.1",
    "jupyterlab>=4.0.9",
    "matplotlib>=3.7.4",
    "multiprocess>=0.70.15",
    "numdifftools>=0.9.41",
    "numpy>=1.25.2",
    "pandas>=2.1",
    "plotly>=5.18",
    "pyarrow>=14.0.2",
    "scikit-learn>=1.3.2",
    "scipy>=1.11.4",
    "seaborn>=0.13.2",
    "swifter>=1.4",
    "tqdm>=4.66.1",
    "xarray>=2023.11",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.ruff]
select = [
  "F",  # pyflakes
  "I",  # isort
  "UP",  # pyupgrade
  "E",  # pycodestyle
  "W",  # warning
]
ignore = [
  # Aim to progressively fix address these codes over time
  "E501",  # Line too long
  "E741",  # Ambiguous variable name: `l`
  "E402",  # Module level import not at top of file
  "UP032",  # Use f-string instead of `format` call
]
